
// Objective-C API for talking to the following Go packages
//
//	bt
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Bt_FRAMEWORK_H__
#define __Bt_FRAMEWORK_H__

#include "Bt.objc.h"
#include "Universe.objc.h"

#endif
